server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hello123456780/microservicecloud-config.git
          #git@github.com:Hello123456780/microservicecloud-config.git
          #git@github.com:zzyybs/microservicecloud-config.git #GitHub上面的git仓库名字

